export enum Events {
  loggedIn = "loggedIn",
  sessionExpired = "sessionExpired",
  loggedOut = "loggedOut",
  invalidCredentials = "invalidCredentials",
  billPaid = "billPaid",
  billCreated = "billCreated",
  failedToCreateBill = "failedToCreateBill",
  billUpdated = "billUpdated",
  debtorCreated = "debtorCreated",
  failedToCreateDebtor = "failedToCreateDebtor",
  failedToFetchBills = "failedToFetchBills",
  failedToDeleteDebtor = "failedToDeleteDebtor",
  debtorDeleted = "debtorDeleted",
  failedToFetchPayments = "failedToFetchPayments",
  paymentCreated = "paymentCreated",
  failedToCreatePayment = "failedToCreatePayment",
  userRegistered = "userRegistered",
  failedToRegisterUser = "failedToRegisterUser",
  paymentDeleted = "paymentDeleted",
  failedToDeletePayment = "failedToDeletePayment",
  failedToFetchData = "failedToFetchData",
}
